# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Image
        run: docker build -f Home-Tab/Home-Tab/Dockerfile -t orangenal/home-tab:latest Home-Tab
      -
        name: Push Image
        run: docker push orangenal/home-tab:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Key
        run: echo {{ secrets.KEY }} >> ~/.ssh/id_rsa
      -
        name: Connect
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p {{ secrets.PORT }}
      -
        name: Enter repo directory
        run: cd /home/orangenal/Home-Tab
      -
        name: Pull repo
        run: git pull
      -
        name: Stop compose
        run: docker-compose down
      -
        name: Start compose
        run: docker-compose up
      -
        name: Disconnect
        run: exit
      -
        name: Clear key
        run: rm ~/.ssh/id_rsa
        #name: Connect and start
        #uses: appleboy/ssh-action@master
        #with:
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #key: ${{ secrets.KEY }}
          #port: ${{ secrets.PORT }}
          #script: |
            #cd /home/orangenal/Home-Tab
            #git pull
            #docker-compose up
